# Generated by Django 4.1.7 on 2023-02-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
