# Generated by Django 4.1.7 on 2023-02-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_log', models.DateTimeField(auto_now_add=True)),
                ('type_log', models.CharField(choices=[('otp', '0'), ('pass', '1')], max_length=10)),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_user', to='login.user', verbose_name='user')),
            ],
        ),
    ]
