# Generated by Django 4.1.7 on 2023-02-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_create_at_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type_log',
            field=models.CharField(choices=[('otp', 'otp'), ('pass', 'pass')], max_length=10),
        ),
    ]
