# Generated by Django 4.1.7 on 2023-02-22 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_log_type_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.RegexValidator(message='Phone number must be entered in the correct format ', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
